Added fields to the Resource model and added image utilities
CruCentralCoast/Keystone pull request #6
Opened 2017-02-23 07:51 UTC by brittanyberlanga

Originally the plan was to just add author, description, and image fields to the resource model; however, I noticed that many of the model objects with image fields declare many of the same functions and I thought making a utilities module for all of them would be useful.

I ran the server locally to make sure my changes didn't break anything, but since I can't actually upload a photo to aws, I wasn't able to fully test everything.

Let me know if you see anything concerning :)

2017-02-26 23:14 UTC, fedorareis commented
not to be nitpicky, but could you fix the styling (mainly the indentation) in the resources file. It is pretty all over the place.

2017-02-27 07:30 UTC, brittanyberlanga commented
@fedorareis Yeah, of course! What specifically needs fixing? Is it the 3 space indentations compared to 2 space indentations?

2017-02-28 06:12 UTC, fedorareis requested changes
There are a number of spots where the closing brace is indented one too few characters. There are a couple instances of lines not being indented to the level they should be (see line 93 of Resources.js).

2017-02-28 06:57 UTC, tylerbwong commented
@fedorareis Resources.js doesn't appear to have a 93rd line. Is there a different example?

2017-03-02 20:39 UTC, fedorareis requested changes
Most of the spots where there is a return in this file the indentation is wrong. Honestly I would recommend just running it through an formatter or an editor with formatting rules set. We are using the standard Node coding style if I remember correctly.

2017-03-02 20:39 UTC, fedorareis commented on models/Resource.js
> +      	return url;
This was the line I was trying to reference. THe return should be indented 2 more times and the curly brace below should be indented one more time.

2017-03-02 22:26 UTC, tylerbwong commented on models/Resource.js
> +      	return url;
@fedorareis I'm pretty sure you're looking at an old commit. The most recent one should be from 2 days ago.

2017-03-02 22:27 UTC, tylerbwong commented on models/Resource.js
> +      	return url;
3d248944d2dc3cc417d5073c786580b7c1c0d9cb is the most recent commit hash.

2017-03-03 21:52 UTC, fedorareis commented on models/Resource.js
> +      	return url;
whoops, totally didn't see that. Then from what I can see everything looks good.

2017-03-03 21:52 UTC, fedorareis approved these changes

2017-03-03 21:53 UTC, merged

2017-03-03 21:53 UTC, fedorareis commented
I will push the updates live this weekend.